import { createHash } from "node:crypto";
import {
  mkdir,
  readFile,
  readdir,
  stat,
  writeFile
} from "node:fs/promises";
import path from "node:path";

const CACHE_PREFIX = "crazy-rummy-static-";
const WORKER_FORMAT_VERSION = 1;
const GENERATED_FILE_PATTERN =
  /^(?:precache-manifest\.[a-f0-9]+\.json|sw(?:\.[a-f0-9]+)?\.js)$/;
const HASHED_ASSET_PATTERN =
  /^assets\/.+-[a-zA-Z0-9_-]{8,}\.[a-zA-Z0-9]+$/;
const VERSIONED_PUBLIC_ASSET_PATTERN =
  /^(?:art|icons|assets\/(?:brand|cards|materials|ui))\/.+\.v[0-9]+\.(?:png|svg|webp)$/;

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function normalizeBasePath(basePath = "/") {
  const value = String(basePath || "/").trim();
  const withLeadingSlash = value.startsWith("/") ? value : `/${value}`;
  return withLeadingSlash.endsWith("/")
    ? withLeadingSlash
    : `${withLeadingSlash}/`;
}

function asUrl(file, basePath = "/") {
  return `${normalizeBasePath(basePath)}${file.split(path.sep).join("/")}`;
}

async function listFiles(directory, relativeDirectory = "") {
  const entries = await readdir(path.join(directory, relativeDirectory), {
    withFileTypes: true
  });
  const files = [];

  for (const entry of entries) {
    const relativePath = path.join(relativeDirectory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await listFiles(directory, relativePath));
    } else if (entry.isFile()) {
      files.push(relativePath);
    }
  }

  return files;
}

export function isVersionedStaticAsset(relativePath) {
  const normalized = relativePath.split(path.sep).join("/");
  return HASHED_ASSET_PATTERN.test(normalized)
    || VERSIONED_PUBLIC_ASSET_PATTERN.test(normalized);
}

export async function describePrecacheAssets(
  distDirectory,
  { basePath = "/" } = {}
) {
  const files = await listFiles(distDirectory);
  const assets = [];

  for (const relativePath of files.sort()) {
    const normalized = relativePath.split(path.sep).join("/");
    if (GENERATED_FILE_PATTERN.test(normalized)
      || !isVersionedStaticAsset(normalized)) {
      continue;
    }

    const absolutePath = path.join(distDirectory, relativePath);
    const [contents, metadata] = await Promise.all([
      readFile(absolutePath),
      stat(absolutePath)
    ]);
    assets.push({
      url: asUrl(relativePath, basePath),
      bytes: metadata.size,
      sha256: sha256(contents)
    });
  }

  return assets;
}

function renderVersionedServiceWorker(manifest) {
  const assetUrls = manifest.assets.map(({ url }) => url);

  return `/* Generated by the Crazy Rummy Vite PWA hook. */
const CACHE_PREFIX = ${JSON.stringify(CACHE_PREFIX)};
const CACHE_NAME = ${JSON.stringify(manifest.cacheName)};
const SHELL_URL = ${JSON.stringify(manifest.navigationShell)};
const NAVIGATION_ROUTES = ${JSON.stringify(manifest.navigationRoutes)};
const ASSET_URLS = ${JSON.stringify(assetUrls)};
const ASSET_PATHS = new Set(ASSET_URLS);

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(ASSET_URLS.map((url) => new Request(url, {
      cache: "reload",
      credentials: "same-origin"
    })));

    const shellResponse = await fetch(SHELL_URL, {
      cache: "reload",
      credentials: "same-origin"
    });
    if (!shellResponse.ok) {
      throw new Error(\`Unable to precache the app shell: \${shellResponse.status}\`);
    }

    await cache.put(SHELL_URL, shellResponse.clone());
    await Promise.all(NAVIGATION_ROUTES.map((route) =>
      cache.put(route, shellResponse.clone())
    ));
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const cacheNames = await caches.keys();
    await Promise.all(cacheNames
      .filter((cacheName) =>
        cacheName.startsWith(CACHE_PREFIX) && cacheName !== CACHE_NAME
      )
      .map((cacheName) => caches.delete(cacheName)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.ok) return response;
      } catch {
        // The cached shell below is the honest offline navigation fallback.
      }

      const cache = await caches.open(CACHE_NAME);
      return (await cache.match(url.pathname))
        || (await cache.match(SHELL_URL))
        || Response.error();
    })());
    return;
  }

  if (ASSET_PATHS.has(url.pathname)) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE_NAME);
      const cached = await cache.match(request);
      return cached || fetch(request);
    })());
  }
});
`;
}

function renderServiceWorkerBootstrap(version) {
  return `/* Generated entry point; changes when the precache version changes. */
importScripts(${JSON.stringify(`./sw.${version}.js`)});
`;
}

export async function generatePwaArtifacts({
  distDirectory,
  revision = "",
  basePath = "/"
}) {
  const normalizedBasePath = normalizeBasePath(basePath);
  const shellPath = path.join(distDirectory, "index.html");
  const shellContents = await readFile(shellPath);
  const navigationShellSha256 = sha256(shellContents);

  const assets = await describePrecacheAssets(distDirectory, {
    basePath: normalizedBasePath
  });
  if (assets.length === 0) {
    throw new Error(
      "PWA generation found no versioned static assets in the final Vite output."
    );
  }

  const version = sha256(JSON.stringify({
    assets,
    navigationShellSha256,
    workerFormatVersion: WORKER_FORMAT_VERSION,
    revision
  })).slice(0, 16);
  const manifest = {
    version,
    cacheName: `${CACHE_PREFIX}${version}`,
    navigationShell: `${normalizedBasePath}index.html`,
    navigationShellSha256,
    navigationRoutes: [
      normalizedBasePath,
      `${normalizedBasePath}rules`
    ],
    assets
  };
  const manifestFilename = `precache-manifest.${version}.json`;
  const versionedWorkerFilename = `sw.${version}.js`;

  await mkdir(distDirectory, { recursive: true });
  await Promise.all([
    writeFile(
      path.join(distDirectory, manifestFilename),
      `${JSON.stringify(manifest, null, 2)}\n`,
      "utf8"
    ),
    writeFile(
      path.join(distDirectory, versionedWorkerFilename),
      renderVersionedServiceWorker(manifest),
      "utf8"
    ),
    writeFile(
      path.join(distDirectory, "sw.js"),
      renderServiceWorkerBootstrap(version),
      "utf8"
    )
  ]);

  return {
    ...manifest,
    manifestFilename,
    serviceWorkerFilename: "sw.js",
    versionedWorkerFilename
  };
}

export function createCrazyRummyPwaPlugin() {
  let outDirectory;
  let basePath = "/";
  let buildFailed = false;
  const revision = process.env.CRAZY_RUMMY_PWA_REVISION ?? "";

  return {
    name: "crazy-rummy-pwa",
    apply: "build",
    transformIndexHtml: revision
      ? {
          order: "post",
          handler() {
            return [{
              tag: "meta",
              attrs: {
                name: "crazy-rummy-build-revision",
                content: revision
              },
              injectTo: "head"
            }];
          }
        }
      : undefined,
    configResolved(config) {
      outDirectory = path.resolve(config.root, config.build.outDir);
      basePath = normalizeBasePath(config.base);
    },
    buildStart() {
      buildFailed = false;
    },
    buildEnd(error) {
      buildFailed = Boolean(error);
    },
    async closeBundle() {
      if (buildFailed) return;
      await generatePwaArtifacts({
        distDirectory: outDirectory,
        revision,
        basePath
      });
    }
  };
}
